### ISSUE TITLE
1.5 years / 18 months doesn't seem to work

### ISSUE THREAD

**Issue by alexander-potemkin** [Kageetai/obsidian-plugin-journal-review#4]
First of all - thank you a lot for the plugin! It's absolutely amazing!

I have a problem, though - I tried to setup `1 years 6 months` and `18 months` time span, but it doesn't work - an appropriate section just doesn't appear...

Is there something I'm doing wrong? Or if it's a bug - what I can provide to fix it?

**Comment by Kageetai** [comment]
Hmm, I had some problems with the view updating when changing settings or new items are created. Does the same happen when you reload Obsidian and open the view?

**Comment by alexander-potemkin** [comment]
Thanks! Yes, I did try to restart Obsidian. A few times, actually.
Is there any kind of debug log or something that I could provide, @Kageetai ?

**Comment by Kageetai** [comment]
Alright, with more inspiration I managed to also look into this and it should be fixed as well. The setting for `18 months` should now work, but it will be shown as `2 years`.
`1 years 6 months` won't work as it doesn't follow the syntax for `number unit`. But I am thinking to redo how the time spans are defined to be more flexible soon.

**Comment by Kageetai** [comment]
That should have been done with `1.0.4`. Same as the other issue, just forgot to update the manifest file etc.

**Comment by alexander-potemkin** [comment]
That's fine, thanks for fixing that! It's so nice to see more granular configuration here!

Yeah, the only one thing now - it's that it says 2 years indeed :)
Is there probably some workaround probably? Like showing months count instead? Or something of the kind?

**Comment by alexander-potemkin** [comment]
Thank you! What about an option: show headers humaniz-ed or not?
This way I will still see my input, which is 18 months, which makes perfect sense?

**Comment by Kageetai** [comment]
Hmm, not. a bad idea, just a toggle to disable the "humanization" of the dates, right?

**Comment by alexander-potemkin** [comment]
Yep. So I will have my input at the right side - which is, probably, not that much 'human', but rather correct and flexible.

**Comment by Kageetai** [comment]
Hey there again,
I finally managed to add a setting toggle to disable "humanization" of the time spans, when rendering. Let me know whether this works well for you.

**Comment by Kageetai** [comment]
Assuming this as done for the time being.

**Comment by alexander-potemkin** [comment]
@Kageetai , apologies - I somehow missed a notification two weeks ago.
I just updated the plugin and humanization indeed works nice, but I discovered there is no '18 months' span in my view... 

I have the following list in my settings:
```
1 months
3 months
6 months
9 months
12 months
18 months
2 years
3 years
```

And 18 months is the only that doesn't work.

Could you please, check that? Or shall I open a new ticket for that? Any important is missing? Please, let me know!

**Comment by Kageetai** [comment]
Hello again,
no worries, always possible to still answer here.
As I had said above, "18 months" would have been grouped together with "2 years".

But on that note, I also just pushed a big release 2.0.0, that entirely changes how the settings work and should also allow more flexibility on that side, with recurring time spans etc.
Can you try your use case with the new version again and with or without "humanization" turned on and see if it works for you?!
Hope it helps.

**Comment by alexander-potemkin** [comment]
Hello and thank you! I've tried a new version, but unfortunately it feels like it work not like intended. I narrowed my settings down to every 1 month, and I'm getting 3, 6, 9, 1 year, 12 months, 2 years...

**Comment by Kageetai** [comment]
Hmm, that sounds a bit like the conversion of the settings to the new format didn't work as expected. Can you maybe delete your settings file for this plugin (in `.obsidian/plugins/journal-review/data.json`) (backup it first if you want) and try again? And if it still happens, maybe share a screenshot of the settings and the file with me? Thx

**Comment by alexander-potemkin** [comment]
Sure, deleted `data.json` and then all settings at `/Users/<...>/.obsidian/plugins/journal-review` - but they remained somehow, so I uninstalled plugin completely and re-installed it - with default settings things are still not as expected - please, find screenshots attached.

Thank you.

<img width="329" alt="RdScreenshot 2023-10-30 at 12 12 55" src="https://github.com/Kageetai/obsidian-plugin-journal-review/assets/2323840/0415faa7-38fb-4aa5-84e1-7ec7938058be">
<img width="830" alt="Screenshot 2023-10-30 at 12 12 49" src="https://github.com/Kageetai/obsidian-plugin-journal-review/assets/2323840/6ac73ad5-b439-40e7-aa6b-b992346608ce">

**Comment by Kageetai** [comment]
Okay, I noticed there was a bug when disabling the humanization (I am not using it myself like that), but I that should be fixed now, with version [2.0.1](https://github.com/Kageetai/obsidian-plugin-journal-review/releases/tag/2.0.1)

**Comment by alexander-potemkin** [comment]
Thank you, it finally works! It seems I can't make it 1, 3, 6, 12, 18, 24 months now, but gives another perspective, though.

Appreciate your help and prompt responses and thank you again for the extension!

**Comment by Kageetai** [comment]
Shouldn't you be able to do this?

![Screenshot 2023-10-30 at 15 44 54](https://github.com/Kageetai/obsidian-plugin-journal-review/assets/1738309/95004b64-ff1c-43ad-a04c-8bec80ff41ba)

But I did notice a bug where identical time spans get adjusted together, seems a quirk from the Obsidian API, that I need to add a fix around.

**Comment by alexander-potemkin** [comment]
The order is different and it's groupped, as opposed to just listed. With the new records display design (I guess it got some background now?) it's quite visually distinctive and hence changes the experience. Does it makes sense?

**Comment by Kageetai** [comment]
To be honest, I am not fully sure what you mean.
Yes, I changed the styling to make the note previews more distinct. And I am grouping them either under the humanized (if enabled) time span relative to now or just the time span settings themselves.
How would you want the grouping imagine to happen?

**Comment by alexander-potemkin** [comment]
Thank you for asking. I understand you originally created it for yourself and I appreciate you listen to my thoughts!

I liked the way I could place them originally: 1 month ago => 3 months ago => 6 months ago => 1 year ago => 1.5 years ago => 2 years ago.
That gave me a prospective on how things changes.

For the colour distinction – I also liked that they are not colour selected, as I have this view opened all the time and I would rather not be distracted.

I hope I managed to express my thoughts, if not - please, do let me know!

**Comment by Kageetai** [comment]
Thank you as well, I appreciate the open discussion and ideas :)

If you are aiming to emulate the settings from before, I think you could do what you are describing like this (and disable humanization):

<img width="783" alt="Screenshot 2023-11-05 at 22 26 07" src="https://github.com/Kageetai/obsidian-plugin-journal-review/assets/1738309/32d924d3-d083-49ba-9ccb-3687d3d895be">

If you want to use the recurrence feature, you can also get more or less the same with this (although I currently can only bundle items under their "titles", and therefore you have several items under "every 6 months"):

<img width="780" alt="Screenshot 2023-11-05 at 22 26 55" src="https://github.com/Kageetai/obsidian-plugin-journal-review/assets/1738309/265a5c72-6ace-44df-b61b-bf425dea07dd">

Does that help and is closer to what you mean?

I can also add a toggle to disable the new styles, I just thought this looks more appealing when using callout styles, but can also make it optional.

**Comment by alexander-potemkin** [comment]
>  although I currently can only bundle items under their "titles", and therefore you have several items under "every 6 months"

yeah, that's exactly my problem :)

> I also just added a toggle to disable the new styles, I just thought this looks more appealing when using callout styles, but can also make it optional. With disabling this new toggle, it should look like the old styles again.

Fantastic! Thank you!

> Thank you as well, I appreciate the open discussion and ideas :)

Glad to hear that :)

**Comment by Kageetai** [comment]
Hey, I think I found another way to make the note titles work for you, with calculating the time difference manually. Try the version [2.0.7](https://github.com/Kageetai/obsidian-plugin-journal-review/releases/tag/2.0.7) :)

**Comment by alexander-potemkin** [comment]
hey and thank you for keep on improving and adding options! :)

I've updated to 2.0.7 and I tried to add first span as '1 month' and then the second one as '6 months', but my '1 month' get increased to '6 months' as well - is it an intended behaviour or something goes not expected?

Btw, as an idea that you didn't ask, but I though to share - probably choosing number of months via drop-down menu as well? It feels like it would be a bit quicker. That's not critical at all - the setup only happens once - sharing it just in case :)

<img width="345" alt="Screenshot 2023-11-16 at 11 56 20" src="https://github.com/Kageetai/obsidian-plugin-journal-review/assets/2323840/759a8cf9-eb1d-4dad-946c-28466350b8eb">

**Comment by Kageetai** [comment]
Hey, I had noticed the issues with the values effecting each other but couldn't reliably reproduce it. I tried a fix now, that should hopefully resolve that. Please update to 2.0.8 :)
Regarding the sliders, I am also not a fan, but unfortunately the default settings elements from Obsidian are very limited and don't allow much flexibility. I think I would stick with the sliders for now to see whether other people also have problems etc...

**Comment by alexander-potemkin** [comment]
Hey, thank you! I'm sorry to say, but the issue is still in place...

To reproduce:
- remove all of the slides (not sure if that's required, but just to make sure it's definitely starts clean)
- create interval that is equal 1 month (not repeating)
- create another interval - set it equals to 3 months -> as you move that slider, the slider above starts moving as well... 

<img width="399" alt="Screenshot 2023-11-28 at 22 06 40" src="https://github.com/Kageetai/obsidian-plugin-journal-review/assets/2323840/580360ed-d0cc-4f7a-9f6c-16cfc1ef3c60">

**Comment by Kageetai** [comment]
Hey, it's me, back again :)
I think I just figured out what the problem was and pushed a fix, can you try if that works for you?
The problem seemed to be only with newly added intervals, that somehow got linked together. But when reloading Obsidian or so, there weren't linked any more. Either way should be fine now.

**Comment by alexander-potemkin** [comment]
Hey, glad to hear from you! :)

Oh, thank you! It's absolutely amazing! It works now!! Thank you so much!!

**Comment by alexander-potemkin** [comment]
If it's not too much, may I kindly ask to not show the date in the view, or have on the same line as the note, for example:
```
2 years ago (2022-01-17):
```
or just
```
2 years ago:
```

As opposed to:
```
2 years ago:
2022-01-17
```
<img width="183" alt="Screenshot 2024-01-17 at 22 22 28" src="https://github.com/Kageetai/obsidian-plugin-journal-review/assets/2323840/ff21c5da-421e-4070-9acd-9d96c37681db">

?

And, as a final piece of beauty - remove highlights from beginning of the note - it looks like they are quoted and that eats precious space and attention.

<img width="32" alt="Screenshot 2024-01-17 at 22 26 11" src="https://github.com/Kageetai/obsidian-plugin-journal-review/assets/2323840/724bc6c3-cda4-4b7b-b7da-39b00d61b8d0">

I will surely understand if that's too much - I really appreciate everything you've done so far, so it's really not that much of the problem, but I thought to ask it - it would make things just absolutely stunning! :)

**Comment by Kageetai** [comment]
Hey,
unfortunately I can't put the time span and the date on the same line, as it's. possible to have more than one note within the "2 years" time span, for example if you change the settings to include +/-1 days etc. Checking whether only one note is rendered and then adding the date directly on the same line, seems unfeasible here, but I will keep it in mind.
I could add a setting to not render the line, meaning not use a quote for the note. For my initial idea, I thought "quoting" these older notes would make sense, but I can also remove it. I just wanted to have a way to differentiate if several notes are rendered one after another, as described above.

**Comment by alexander-potemkin** [comment]
Hey, apologies for the delay!

If that won't be too much to ask - yeah, could you please, add an option to remove the title? It's only feel that it would be better, if I have an option to remove note's name - leaving just '2 years ago', etc?

It feels like that shall be a perfect match =)

**Comment by Kageetai** [comment]
Hey there,
I quickly added two settings on a quieter Friday to disable the quote and hide the note title, update to version `2.2.0` to get it :)

**Comment by alexander-potemkin** [comment]
Hey and thank you! It's a wonderful Friday and I'm a very happy man :)

Thank you very very much, I really appreciate everything you did and keep doing! And a special thank you for listening for all of the wishes - I couldn't expect they come true ❤️

**Comment by Kageetai** [comment]
No worries, it's satisfying to do these kinda things and make someone happy and motivates to continue :)

**Comment by alexander-potemkin** [comment]
Thank you! I really enjoy using your extension - it's one of the main thing I do use in Obsidian :)
